version: "3.7"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    #restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: 'bitnami/kafka:2.8.1'
    #restart: always
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092

  database:
    restart: always
    image: bitnami/postgresql:11
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - type: bind
        source: ./db/data/postgres
        target: /var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile 
    #restart: always
    depends_on:
      - zookeeper
      - kafka
      - database
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
    volumes:
      - ./producer/index.js:/app/index.js
    ports:
      - 3000:3000
      
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile 
    #restart: always
    depends_on:
      - zookeeper
      - kafka
      - database
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
    volumes:
      - ./consumer/index.js:/app/index.js
    ports:
      - 3001:3000